Init
cloudposse/openvpn-api pull request #1
Opened 2017-03-01 16:40 UTC by goruha

2017-03-02 05:45 UTC, osterman requested changes
Remove `release/openvpn-api` from git

2017-03-02 05:45 UTC, osterman commented on .build-harness
> +export SHELL = /bin/bash
Do not commit this file

2017-03-02 05:45 UTC, osterman commented on .travis.yml
> +  api_key: $GITHUB_OAUTH_TOKEN
Use `GITHUB_API_KEY` for correctness.

2017-03-02 05:45 UTC, osterman commented on src/api/openvpn.go
> +	file := "/etc/openvpn/clients/" + name + "/" + name + "-combined.ovpn"
Lets make sure that `name` is alphanumeric.

2017-03-02 05:45 UTC, osterman commented on src/api/openvpn.go
> +
Lets make sure that `name` is alphanumeric.

2017-03-02 05:45 UTC, osterman commented on src/api/openvpn.go
> +	cmd := exec.Command("easyrsa", "build-client-full", user, "nopass")
Lets make sure that `user` is alphanumeric.

2017-03-02 05:45 UTC, osterman commented on src/cmd/root.go
> +	Short: "Use Openvpn API to create users and fetch predefined openvpn configs",
OpenVPN

2017-03-02 05:45 UTC, osterman commented on src/cmd/root.go
> +Use Openvpn API to create users and fetch predefined openvpn configs.
OpenVPN (use proper case)

2017-03-02 05:45 UTC, osterman commented on src/server/server.go
> +		name := c.Param("name")
Lets make sure that `name` is alphanumeric.

2017-03-06 21:18 UTC, osterman commented on .gitignore
> +
add `.build-harness` here

2017-03-06 21:19 UTC, osterman commented on .travis.yml
> +    - release/$APP_darwin_386
What do you think about using wildcards here? https://github.com/cloudposse/sudosh/blob/master/.travis.yml#L27

2017-03-06 21:20 UTC, osterman commented on src/api/openvpn.go
> +
Please annotate all these functions so it's clear what they do

2017-03-07 13:28 UTC, goruha commented on .build-harness
> +export SHELL = /bin/bash
Done

2017-03-07 13:32 UTC, goruha commented on .travis.yml
> +  api_key: $GITHUB_OAUTH_TOKEN
Done

2017-03-07 13:32 UTC, goruha commented on .gitignore
> +
Done

2017-03-07 13:34 UTC, goruha commented on .travis.yml
> +    - release/$APP_darwin_386
Nice.

Thanks.

2017-03-07 13:35 UTC, goruha commented on src/cmd/root.go
> +Use Openvpn API to create users and fetch predefined openvpn configs.
Done

2017-03-07 13:36 UTC, goruha commented on src/cmd/root.go
> +	Short: "Use Openvpn API to create users and fetch predefined openvpn configs",
Done

2017-03-07 13:58 UTC, goruha commented on src/server/server.go
> +		name := c.Param("name")
Done

2017-03-07 13:59 UTC, goruha commented on src/api/openvpn.go
> +	cmd := exec.Command("easyrsa", "build-client-full", user, "nopass")
Done

2017-03-07 13:59 UTC, goruha commented on src/api/openvpn.go
> +
Done

2017-03-07 13:59 UTC, goruha commented on src/api/openvpn.go
> +	file := "/etc/openvpn/clients/" + name + "/" + name + "-combined.ovpn"
Done

2017-03-07 14:09 UTC, goruha commented on src/api/openvpn.go
> +
Done

2017-03-07 15:20 UTC, osterman commented on src/api/openvpn.go
>  func deleteFileSafety(file string) (err error) {
do you mean `deleteFileSafely` instead?

2017-03-07 15:21 UTC, osterman commented on src/server/server.go
> +	router.Use(validation.ValidatePathParam("name", validator.RegExp{"^[a-zA-Z0-9]*$"}))
Name should contain at least 1 character. Change `*` to `+`.

2017-03-07 15:22 UTC, osterman requested changes
Please fix regex

2017-03-07 15:56 UTC, goruha commented on src/api/openvpn.go
>  func deleteFileSafety(file string) (err error) {
Right. 

typo.

2017-03-07 15:56 UTC, goruha commented on src/api/openvpn.go
>  func deleteFileSafety(file string) (err error) {
Done

2017-03-07 15:56 UTC, goruha commented on src/server/server.go
> +	router.Use(validation.ValidatePathParam("name", validator.RegExp{"^[a-zA-Z0-9]*$"}))
Done

2017-03-07 16:00 UTC, osterman approved these changes

2017-03-09 04:45 UTC, merged